import * as ast from "../parser/ast";
import { Operator } from "../lexer/token";
import { LLVMIRBuilder, LLVMValue } from "./builder";
import { declareBuiltins } from "./builtin";
import { SemanticAnalyzer } from "../semantic/semantic";
import { SymbolTableImpl, VariableSymbol, FunctionSymbol, Type, i32Type, boolType, unitType, PrimitiveType, isNever } from "../semantic/info";

/**
 * CodeGenerator traverses the AST and generates LLVM IR.
 * Implements the Visitor pattern used throughout the compiler.
 */
export class CodeGenerator implements ast.Visitor<LLVMValue | null> {
  private builder: LLVMIRBuilder;
  private analyzer: SemanticAnalyzer;
  private symbolTable: SymbolTableImpl; // Keep for function lookup (global scope)
  private currentFunction: ast.FuncItem | null = null;
  private currentReturnType: string | null = null;
  private loopStack: { breakLabel: string; continueLabel: string }[] = [];

  constructor(analyzer: SemanticAnalyzer) {
    this.analyzer = analyzer;
    this.symbolTable = analyzer.getSymbolTable(); // Get symbol table for function lookup
    this.builder = new LLVMIRBuilder();
  }

  /**
   * Generate LLVM IR for an entire crate (module).
   */
  generate(crate: ast.Crate): string {
    // Emit module header
    this.builder.emitComment("Generated by RComp");
    this.builder.emitEmptyLine();

    // Declare built-in functions
    declareBuiltins(this.builder);
    this.builder.emitEmptyLine();

    // Visit all items
    ast.visit(crate, this);

    return this.builder.getIR();
  }

  /**
   * Visit a crate (module root).
   */
  onCrate(node: ast.Crate, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Emit global constants first
    for (const item of node.items) {
      if (item.kind === ast.ASTType.ConstItem) {
        ast.visit(item, this);
      }
    }

    // Emit functions
    for (const item of node.items) {
      if (item.kind === ast.ASTType.FnItem) {
        ast.visit(item, this);
      }
    }
    return null;
  }

  /**
   * Visit a function definition.
   */
  onFn(node: ast.FuncItem, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    this.currentFunction = node;

    // Get function symbol to retrieve type information
    const funcSym = this.symbolTable.lookupFunction(node.name);
    if (!funcSym) {
      throw new Error(`Function ${node.name} not found in symbol table`);
    }

    // Map return type
    this.currentReturnType = this.builder.getType(funcSym.returnType);

    // Special case: main function should return i32 (even if semantic type is unit)
    if (funcSym.isMain && this.currentReturnType === "void") {
      this.currentReturnType = "i32";
    }

    // Map parameters to LLVM types
    const params = node.params.map((p) => {
      let paramName: string;
      if (p.pattern.kind === ast.ASTType.IdentifierPattern) {
        paramName = (p.pattern as ast.IdentifierPattern).name;
      } else {
        paramName = `param`;
      }
      const paramType = this.builder.getType(funcSym.params[node.params.indexOf(p)]!);
      return { name: paramName, type: paramType };
    });

    // Start function definition
    this.builder.define(this.currentReturnType, node.name, params);
    this.builder.label("entry");

    // Clear allocations from previous function
    this.builder.clearAllocations();

    // Allocate space for local variables (parameters first)
    for (const param of node.params) {
      if (param.pattern.kind === ast.ASTType.IdentifierPattern) {
        const paramName = (param.pattern as ast.IdentifierPattern).name;
        const paramType = this.builder.getType(funcSym.params[node.params.indexOf(param)]!);

        // Allocate stack space and store parameter value
        this.builder.alloca(paramName, paramType);
        this.builder.store(`%${paramName}`, paramType, paramName);
      }
    }

    // Generate function body
    if (node.body) {
      ast.visit(node.body, this);

      // Add implicit return if none exists
      if (!this.blockHasReturn(node.body)) {
        if (this.currentReturnType === "void") {
          this.builder.ret();
        } else if (funcSym.isMain) {
          // main 函数隐式返回 0
          this.builder.ret("0");
        }
      }
    } else if (this.currentReturnType !== "void") {
      // Non-void function without body - error
      throw new Error(`Function ${node.name} has non-void return type but no body`);
    } else {
      // Void function without body
      this.builder.ret();
    }

    this.builder.endFunction();

    this.currentFunction = null;
    this.currentReturnType = null;
    return null;
  }

  /**
   * Check if a block has a return statement.
   */
  private blockHasReturn(block: ast.BlockExpr): boolean {
    for (const stmt of block.statements) {
      if (stmt.kind === ast.ASTType.ExprStatement) {
        const exprStmt = stmt as ast.ExprStatement;
        if (this.exprHasReturn(exprStmt.expr)) {
          return true;
        }
      }
    }
    return false;
  }

  /**
   * Check if an expression has a return statement.
   */
  private exprHasReturn(expr: ast.Expr): boolean {
    if (expr.kind === ast.ASTType.ReturnExpr) {
      return true;
    }
    if (expr.kind === ast.ASTType.BlockExpr) {
      return this.blockHasReturn(expr);
    }
    if (expr.kind === ast.ASTType.IfExpr) {
      const ifExpr = expr as ast.IfExpr;
      const thenHas = this.exprHasReturn(ifExpr.then);
      const elseHas = ifExpr.else ? this.exprHasReturn(ifExpr.else) : false;
      return thenHas && elseHas;
    }
    return false;
  }

  /**
   * Check if an expression terminates (ends with break, continue, or return).
   */
  private exprTerminates(expr: ast.Expr | ast.Statement): boolean {
    // Check if it's a break, continue, or return
    if (expr.kind === ast.ASTType.BreakExpr ||
        expr.kind === ast.ASTType.ContinueExpr ||
        expr.kind === ast.ASTType.ReturnExpr) {
      return true;
    }

    // Check if it's a block with a terminating statement
    if (expr.kind === ast.ASTType.BlockExpr) {
      const block = expr as ast.BlockExpr;
      for (const stmt of block.statements) {
        if (this.exprTerminates(stmt)) {
          return true;
        }
      }
      if (block.expr && this.exprTerminates(block.expr)) {
        return true;
      }
      return false;
    }

    // Check if it's an if expression where both branches terminate
    if (expr.kind === ast.ASTType.IfExpr) {
      const ifExpr = expr as ast.IfExpr;
      const thenTerminates = this.exprTerminates(ifExpr.then);
      const elseTerminates = ifExpr.else ? this.exprTerminates(ifExpr.else) : false;
      return thenTerminates && elseTerminates;
    }

    // Check if it's an expression statement with a terminating expression
    if (expr.kind === ast.ASTType.ExprStatement) {
      const exprStmt = expr as ast.ExprStatement;
      return this.exprTerminates(exprStmt.expr);
    }

    return false;
  }

  /**
   * Visit a block expression.
   */
  onBlock(node: ast.BlockExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Visit all statements
    for (const stmt of node.statements) {
      ast.visit(stmt, this);
    }

    // Handle block expression (if present)
    let blockValue: LLVMValue | null = null;
    if (node.expr) {
      const value = ast.visit(node.expr, this);
      if (value) {
        blockValue = value;
      }
    }

    return blockValue;
  }

  /**
   * Visit a literal expression.
   */
  onLiteralExpr(node: ast.LiteralExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    let value: string;
    let type: string;

    switch (node.type) {
      case "integer":
        value = this.builder.literalI32(parseInt(node.value, 10));
        type = "i32";
        break;
      case "bool":
        value = this.builder.literalBool(node.value === "true");
        type = "i1";
        break;
      default:
        throw new Error(`Unsupported literal type: ${node.type}`);
    }

    return { register: value, type, isLValue: false };
  }

  /**
   * Visit a binary expression.
   */
  onBinaryExpr(node: ast.BinaryExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    // Check if this is an assignment operator
    const assignmentOps: Operator[] = ["=", "+=", "-=", "*=", "/=", "%="];

    if (assignmentOps.includes(node.operator)) {
      return this.handleAssignment(node);
    }

    // Generate left and right operands
    const left = ast.visit(node.operand[0], this)!;
    const right = ast.visit(node.operand[1], this)!;

    // Get result type from expression
    const resultType = left.type; // Simplified: use left operand type

    // Check if this is a comparison operation
    const comparisonOps: Operator[] = ["==", "!=", "<", ">", "<=", ">="];
    if (comparisonOps.includes(node.operator)) {
      const cond = this.builder.mapComparisonOperator(node.operator);
      const resultReg = this.builder.icmp(cond, left.register, right.register);
      return { register: resultReg, type: "i1", isLValue: false };
    } else {
      // Arithmetic operation
      const resultReg = this.builder.binop(node.operator, left.register, right.register, resultType);
      return { register: resultReg, type: resultType, isLValue: false };
    }
  }

  /**
   * Handle assignment expressions.
   */
  private handleAssignment(node: ast.BinaryExpr): LLVMValue {
    const leftExpr = node.operand[0];
    const rightExpr = node.operand[1];
    const op = node.operator;

    // Left operand must be an lvalue (PathExpr for variables)
    if (leftExpr.kind !== ast.ASTType.PathExpr) {
      throw new Error("Invalid assignment target: only variables supported");
    }

    // Generate right-hand side value
    let value = ast.visit(rightExpr, this)!;

    // For compound assignments, we need to load the current value first
    if (op !== "=") {
      const varName = leftExpr.segs[0]!;
      const currentValue = this.builder.load(varName);

      // Apply the operation
      const baseOp = op.substring(0, op.length - 1) as Operator;
      value = {
        register: this.builder.binop(baseOp, currentValue.register, value.register, value.type),
        type: value.type,
        isLValue: false
      };
    }

    // Store the value
    const varName = leftExpr.segs[0]!;
    this.builder.store(value.register, value.type, varName);

    return value;
  }

  /**
   * Visit a unary expression.
   */
  onUnaryExpr(node: ast.UnaryExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    const operand = ast.visit(node.operand, this)!;
    const resultReg = this.builder.unaryOp(node.operator, operand.register, operand.type);
    return { register: resultReg, type: operand.type, isLValue: false };
  }

  /**
   * Visit a path expression (variable reference).
   */
  onPathExpr(node: ast.PathExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    if (node.segs.length !== 1) {
      throw new Error("Complex paths not supported in MVP");
    }

    const varName = node.segs[0]!;

    // Get type from semantic analysis
    const varType = this.analyzer.getNodeType(node);
    if (!varType) {
      throw new Error(`Type not found for variable: ${varName}`);
    }

    const llvmType = this.builder.getType(varType);

    // Load from stack allocation
    const loaded = this.builder.load(varName);
    return { register: loaded.register, type: llvmType, isLValue: false };
  }

  /**
   * Visit a function call.
   */
  onCallExpr(node: ast.CallExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get function name
    let funcName: string;
    if (node.value.kind === ast.ASTType.PathExpr) {
      funcName = (node.value as ast.PathExpr).segs.join("::");
    } else {
      throw new Error("Complex function calls not supported in MVP");
    }

    // Look up function symbol
    const funcSym = this.symbolTable.lookupFunction(funcName);
    if (!funcSym) {
      throw new Error(`Undefined function: ${funcName}`);
    }

    // Generate arguments
    const argValues = node.param.map((arg) => ast.visit(arg, this)!);
    const args = argValues.map((v) => ({ value: v.register, type: v.type }));

    // Get return type
    const retType = this.builder.getType(funcSym.returnType);

    // Emit call
    const resultReg = this.builder.call(retType, funcName, args);

    if (resultReg) {
      return { register: resultReg, type: retType, isLValue: false };
    } else {
      return null;
    }
  }

  /**
   * Visit a let statement (variable declaration).
   */
  onLet(node: ast.LetStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    let varName: string;
    if (node.pattern.kind === ast.ASTType.IdentifierPattern) {
      varName = (node.pattern as ast.IdentifierPattern).name;
    } else {
      throw new Error("Only identifier patterns supported in MVP");
    }

    // Get variable type from semantic analysis
    const patternType = this.analyzer.getNodeType(node.pattern);
    if (!patternType) {
      throw new Error(`Type not found for variable ${varName}`);
    }

    const varType = this.builder.getType(patternType);

    // Allocate stack space
    this.builder.alloca(varName, varType);

    // Store initial value if provided
    if (node.expr) {
      const initValue = ast.visit(node.expr, this)!;
      this.builder.store(initValue.register, varType, varName);
    }
    return null;
  }

  /**
   * Visit a return expression.
   */
  onReturnExpr(node: ast.ReturnExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (node.expr) {
      const value = ast.visit(node.expr, this)!;
      if (this.currentReturnType !== "void") {
        this.builder.ret(value.register);
      } else {
        throw new Error("Cannot return value from void function");
      }
    } else {
      if (this.currentReturnType === "void") {
        this.builder.ret();
      } else {
        throw new Error("Must return value from non-void function");
      }
    }
    return null;
  }

  /**
   * Visit an if expression.
   */
  onIf(node: ast.IfExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Generate condition
    const cond = ast.visit(node.cond, this)!;

    // Create labels
    const thenLabel = this.builder.freshLabel("if.then");
    const elseLabel = this.builder.freshLabel("if.else");
    const endLabel = this.builder.freshLabel("if.end");

    // Conditional branch
    this.builder.condBr(cond.register, thenLabel, elseLabel);

    // Then block
    this.builder.label(thenLabel);
    const thenValue = ast.visit(node.then, this);
    // Only branch to end if the then block doesn't already terminate
    if (!this.exprTerminates(node.then)) {
      this.builder.br(endLabel);
    }

    // Else block (if present)
    let elseValue: LLVMValue | null = null;
    if (node.else) {
      this.builder.label(elseLabel);
      const visitedElse = ast.visit(node.else, this);
      elseValue = visitedElse ?? null;
      // Only branch to end if the else block doesn't already terminate
      if (!this.exprTerminates(node.else)) {
        this.builder.br(endLabel);
      }
    } else {
      this.builder.label(elseLabel);
      this.builder.br(endLabel);
    }

    // Merge block (only if we haven't terminated)
    const thenTerminates = this.exprTerminates(node.then);
    const elseTerminates = node.else ? this.exprTerminates(node.else) : false;
    if (!thenTerminates || !elseTerminates) {
      this.builder.label(endLabel);
    }

    // Handle if-value (if both branches produce values)
    if (thenValue && elseValue && thenValue.type === elseValue.type) {
      const phiReg = this.builder.phi(thenValue.type, [
        { value: thenValue.register, label: thenLabel },
        { value: elseValue.register, label: elseLabel },
      ]);
      return { register: phiReg, type: thenValue.type, isLValue: false };
    }

    return null;
  }

  /**
   * Visit a while expression.
   */
  onWhile(node: ast.WhileExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Create labels
    const condLabel = this.builder.freshLabel("while.cond");
    const bodyLabel = this.builder.freshLabel("while.body");
    const endLabel = this.builder.freshLabel("while.end");

    // Push loop context onto stack
    this.loopStack.push({
      breakLabel: endLabel,
      continueLabel: condLabel
    });

    // Entry: branch to condition
    this.builder.br(condLabel);

    // Condition block
    this.builder.label(condLabel);
    const cond = ast.visit(node.cond, this)!;
    this.builder.condBr(cond.register, bodyLabel, endLabel);

    // Body block
    this.builder.label(bodyLabel);
    ast.visit(node.body, this);
    this.builder.br(condLabel);

    // End block
    this.builder.label(endLabel);

    // Pop loop context
    this.loopStack.pop();

    return null;
  }

  /**
   * Visit a break expression.
   */
  onBreakExpr(node: ast.BreakExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (this.loopStack.length === 0) {
      throw new Error("break statement outside of loop");
    }

    const breakLabel = this.loopStack[this.loopStack.length - 1]!.breakLabel;

    // Note: while loops ignore break values (unlike loop expressions)
    if (node.expr) {
      ast.visit(node.expr, this);
    }

    this.builder.br(breakLabel);
    return null;
  }

  /**
   * Visit a continue expression.
   */
  onContinueExpr(_node: ast.ContinueExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (this.loopStack.length === 0) {
      throw new Error("continue statement outside of loop");
    }

    const continueLabel = this.loopStack[this.loopStack.length - 1]!.continueLabel;
    this.builder.br(continueLabel);
    return null;
  }

  /**
   * Visit an expression statement.
   */
  onExprStatement(node: ast.ExprStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    ast.visit(node.expr, this);
    return null;
  }

  /**
   * Visit an empty statement.
   */
  onEmptyStatement(_node: ast.EmptyStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    return null;
  }

  /**
   * Visit const item (global constant).
   */
  onConst(node: ast.ConstItem, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // For now, treat const as a global variable
    const sym = this.symbolTable.lookupVariable(node.name);
    if (!sym) {
      throw new Error(`Const ${node.name} not found in symbol table`);
    }

    const varType = this.builder.getType(sym.type);

    // Evaluate constant value
    if (node.val && node.val.kind === ast.ASTType.LiteralExpr) {
      const lit = node.val as ast.LiteralExpr;
      let value: string;
      if (lit.type === "integer") {
        value = this.builder.literalI32(parseInt(lit.value, 10));
      } else if (lit.type === "bool") {
        value = this.builder.literalBool(lit.value === "true");
      } else {
        throw new Error(`Unsupported const literal type: ${lit.type}`);
      }
      this.builder.emitInstruction(`@${node.name} = global ${varType} ${value}`);
    } else {
      throw new Error("Only literal constants supported in MVP");
    }
    return null;
  }

  /**
   * Default handler for unhandled node types.
   */
  default(node: ast.ASTNode, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    throw new Error(`Unhandled AST node type: ${ast.ASTType[node.kind]}`);
  }
}
