import * as ast from "../parser/ast";
import { Operator } from "../lexer/token";
import { LLVMIRBuilder, LLVMValue } from "./builder";
import { declareBuiltins } from "./builtin";
import { SemanticAnalyzer } from "../semantic/semantic";
import { SymbolTableImpl, VariableSymbol, FunctionSymbol, Type, i32Type, boolType, unitType, PrimitiveType, isNever } from "../semantic/info";

/**
 * CodeGenerator traverses the AST and generates LLVM IR.
 * Implements the Visitor pattern used throughout the compiler.
 */
export class CodeGenerator implements ast.Visitor<LLVMValue | null> {
  private builder: LLVMIRBuilder;
  private analyzer: SemanticAnalyzer;
  private symbolTable: SymbolTableImpl; // Keep for function lookup (global scope)
  private currentFunction: ast.FuncItem | null = null;
  private currentReturnType: string | null = null;
  private loopStack: { breakLabel: string; continueLabel: string }[] = [];

  constructor(analyzer: SemanticAnalyzer) {
    this.analyzer = analyzer;
    this.symbolTable = analyzer.getSymbolTable(); // Get symbol table for function lookup
    this.builder = new LLVMIRBuilder();
  }

  /**
   * Generate LLVM IR for an entire crate (module).
   */
  generate(crate: ast.Crate): string {
    // Emit module header
    this.builder.emitComment("Generated by RComp");
    this.builder.emitEmptyLine();

    // Declare built-in functions
    declareBuiltins(this.builder);
    this.builder.emitEmptyLine();

    // Visit all items
    ast.visit(crate, this);

    return this.builder.getIR();
  }

  /**
   * Visit a crate (module root).
   */
  onCrate(node: ast.Crate, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Emit struct type definitions first
    for (const item of node.items) {
      if (item.kind === ast.ASTType.StructItem) {
        ast.visit(item, this);
      }
    }

    // Emit global constants
    for (const item of node.items) {
      if (item.kind === ast.ASTType.ConstItem) {
        ast.visit(item, this);
      }
    }

    // Emit impl blocks (impl functions)
    for (const item of node.items) {
      if (item.kind === ast.ASTType.InherentImpl) {
        ast.visit(item, this);
      }
    }

    // Emit functions
    for (const item of node.items) {
      if (item.kind === ast.ASTType.FnItem) {
        ast.visit(item, this);
      }
    }
    return null;
  }

  /**
   * Visit a function definition.
   */
  onFn(node: ast.FuncItem, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    this.currentFunction = node;

    // Get function symbol to retrieve type information
    const funcSym = this.symbolTable.lookupFunction(node.name);
    if (!funcSym) {
      throw new Error(`Function ${node.name} not found in symbol table`);
    }

    // Map return type
    this.currentReturnType = this.builder.getType(funcSym.returnType);

    // Special case: main function should return i32 (even if semantic type is unit)
    if (funcSym.isMain && this.currentReturnType === "void") {
      this.currentReturnType = "i32";
    }

    // Map parameters to LLVM types
    const params = node.params.map((p) => {
      let paramName: string;
      if (p.pattern.kind === ast.ASTType.IdentifierPattern) {
        paramName = (p.pattern as ast.IdentifierPattern).name;
      } else {
        paramName = `param`;
      }
      const paramType = this.builder.getType(funcSym.params[node.params.indexOf(p)]!);
      return { name: paramName, type: paramType };
    });

    // Handle self parameter for impl methods
    let selfParamType: string | undefined;
    if (funcSym.self) {
      // For impl methods, self is always passed as a pointer (ptr)
      // This works for both &self and &mut self
      selfParamType = "ptr";
      // Add self as the first parameter
      params.unshift({ name: "self", type: selfParamType });
    }

    // Start function definition
    this.builder.define(this.currentReturnType, node.name, params);
    this.builder.label("entry");

    // Clear allocations from previous function
    this.builder.clearAllocations();

    // Allocate space for self parameter first (for impl methods)
    if (funcSym.self && selfParamType) {
      // Allocate stack space for self
      this.builder.alloca("self", selfParamType);
      // Store the self parameter value
      this.builder.store("%self", selfParamType, "self");
    }

    // Allocate space for local variables (parameters first)
    for (const param of node.params) {
      if (param.pattern.kind === ast.ASTType.IdentifierPattern) {
        const paramName = (param.pattern as ast.IdentifierPattern).name;
        const paramType = this.builder.getType(funcSym.params[node.params.indexOf(param)]!);

        // Allocate stack space and store parameter value
        this.builder.alloca(paramName, paramType);
        this.builder.store(`%${paramName}`, paramType, paramName);
      }
    }

    // Generate function body
    if (node.body) {
      const blockResult = ast.visit(node.body, this);

      // Handle implicit return (last expression without semicolon)
      if (!this.blockHasReturn(node.body)) {
        if (blockResult && blockResult.register) {
          // The block returned a value (implicit return)
          if (this.currentReturnType === "void") {
            this.builder.ret();
          } else {
            // For lvalues (like struct expressions), load the value before returning
            if (blockResult.isLValue) {
              const loadedReg = this.builder.freshRegister();
              this.builder.emitInstruction(`${loadedReg} = load ${blockResult.type}, ptr ${blockResult.register}`);
              this.builder.ret(loadedReg, blockResult.type);
            } else {
              this.builder.ret(blockResult.register, blockResult.type);
            }
          }
        } else if (node.body.expr) {
          // Fallback: The block has an expression but didn't return a value
          // This shouldn't happen, but handle it gracefully
          if (this.currentReturnType === "void") {
            this.builder.ret();
          } else if (funcSym.isMain) {
            this.builder.ret("0");
          } else {
            this.builder.ret("undef");
          }
        } else if (this.currentReturnType === "void") {
          this.builder.ret();
        } else if (funcSym.isMain) {
          // main 函数隐式返回 0
          this.builder.ret("0");
        } else {
          // Non-void function without return - this might be an error
          // For now, add a ret instruction to avoid LLVM errors
          this.builder.ret("undef");
        }
      }
    } else if (this.currentReturnType !== "void") {
      // Non-void function without body - error
      throw new Error(`Function ${node.name} has non-void return type but no body`);
    } else {
      // Void function without body
      this.builder.ret();
    }

    this.builder.endFunction();

    this.currentFunction = null;
    this.currentReturnType = null;
    return null;
  }

  /**
   * Check if a block has a return statement.
   */
  private blockHasReturn(block: ast.BlockExpr): boolean {
    for (const stmt of block.statements) {
      if (stmt.kind === ast.ASTType.ExprStatement) {
        const exprStmt = stmt as ast.ExprStatement;
        if (this.exprHasReturn(exprStmt.expr)) {
          return true;
        }
      }
    }
    return false;
  }

  /**
   * Check if an expression has a return statement.
   */
  private exprHasReturn(expr: ast.Expr): boolean {
    if (expr.kind === ast.ASTType.ReturnExpr) {
      return true;
    }
    if (expr.kind === ast.ASTType.BlockExpr) {
      return this.blockHasReturn(expr);
    }
    if (expr.kind === ast.ASTType.IfExpr) {
      const ifExpr = expr as ast.IfExpr;
      const thenHas = this.exprHasReturn(ifExpr.then);
      const elseHas = ifExpr.else ? this.exprHasReturn(ifExpr.else) : false;
      return thenHas && elseHas;
    }
    return false;
  }

  /**
   * Check if an expression terminates (ends with break, continue, or return).
   */
  private exprTerminates(expr: ast.Expr | ast.Statement): boolean {
    // Check if it's a break, continue, or return
    if (expr.kind === ast.ASTType.BreakExpr ||
        expr.kind === ast.ASTType.ContinueExpr ||
        expr.kind === ast.ASTType.ReturnExpr) {
      return true;
    }

    // Check if it's a block with a terminating statement
    if (expr.kind === ast.ASTType.BlockExpr) {
      const block = expr as ast.BlockExpr;
      for (const stmt of block.statements) {
        if (this.exprTerminates(stmt)) {
          return true;
        }
      }
      if (block.expr && this.exprTerminates(block.expr)) {
        return true;
      }
      return false;
    }

    // Check if it's an if expression where both branches terminate
    if (expr.kind === ast.ASTType.IfExpr) {
      const ifExpr = expr as ast.IfExpr;
      const thenTerminates = this.exprTerminates(ifExpr.then);
      const elseTerminates = ifExpr.else ? this.exprTerminates(ifExpr.else) : false;
      return thenTerminates && elseTerminates;
    }

    // Check if it's an expression statement with a terminating expression
    if (expr.kind === ast.ASTType.ExprStatement) {
      const exprStmt = expr as ast.ExprStatement;
      return this.exprTerminates(exprStmt.expr);
    }

    return false;
  }

  /**
   * Visit a block expression.
   */
  onBlock(node: ast.BlockExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Visit all statements
    for (const stmt of node.statements) {
      ast.visit(stmt, this);
    }

    // Handle block expression (if present)
    let blockValue: LLVMValue | null = null;
    if (node.expr) {
      const value = ast.visit(node.expr, this);
      if (value) {
        blockValue = value;
        // For lvalues, we need to load the value for use in expressions
        // But keep it as lvalue so the caller can decide what to do
      }
    }

    return blockValue;
  }

  /**
   * Visit a literal expression.
   */
  onLiteralExpr(node: ast.LiteralExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    let value: string;
    let type: string;

    switch (node.type) {
      case "integer":
        value = this.builder.literalI32(parseInt(node.value, 10));
        type = "i32";
        break;
      case "bool":
        value = this.builder.literalBool(node.value === "true");
        type = "i1";
        break;
      default:
        throw new Error(`Unsupported literal type: ${node.type}`);
    }

    return { register: value, type, isLValue: false };
  }

  /**
   * Visit a binary expression.
   */
  onBinaryExpr(node: ast.BinaryExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    // Check if this is an assignment operator
    const assignmentOps: Operator[] = ["=", "+=", "-=", "*=", "/=", "%="];

    if (assignmentOps.includes(node.operator)) {
      return this.handleAssignment(node);
    }

    // Generate left and right operands
    const left = ast.visit(node.operand[0], this)!;
    const right = ast.visit(node.operand[1], this)!;

    // Get result type from expression
    const resultType = left.type; // Simplified: use left operand type

    // Check if this is a comparison operation
    const comparisonOps: Operator[] = ["==", "!=", "<", ">", "<=", ">="];
    if (comparisonOps.includes(node.operator)) {
      const cond = this.builder.mapComparisonOperator(node.operator);

      // Handle type mismatches in comparisons
      let leftReg = left.register;
      let rightReg = right.register;
      let cmpType = left.type;

      // If types differ, extend the smaller type to match the larger type
      if (left.type !== right.type) {
        if (left.type === "i64" && right.type === "i32") {
          // Extend right to i64
          rightReg = this.builder.zext(rightReg, "i32", "i64");
          cmpType = "i64";
        } else if (left.type === "i32" && right.type === "i64") {
          // Extend left to i64
          leftReg = this.builder.zext(leftReg, "i32", "i64");
          cmpType = "i64";
        }
      }

      const resultReg = this.builder.icmp(cond, leftReg, rightReg, cmpType);
      return { register: resultReg, type: "i1", isLValue: false };
    } else {
      // Arithmetic operation
      const resultReg = this.builder.binop(node.operator, left.register, right.register, resultType);
      return { register: resultReg, type: resultType, isLValue: false };
    }
  }

  /**
   * Handle assignment expressions.
   */
  private handleAssignment(node: ast.BinaryExpr): LLVMValue {
    const leftExpr = node.operand[0];
    const rightExpr = node.operand[1];
    const op = node.operator;

    // Left operand must be an lvalue (PathExpr, IndexExpr, or FieldExpr)
    if (leftExpr.kind !== ast.ASTType.PathExpr &&
        leftExpr.kind !== ast.ASTType.IndexExpr &&
        leftExpr.kind !== ast.ASTType.FieldExpr) {
      throw new Error("Invalid assignment target: only variables, array indexing, and field access supported");
    }

    // Generate right-hand side value
    let value = ast.visit(rightExpr, this)!;

    // For compound assignments, we need to load the current value first
    if (op !== "=") {
      let currentValue: LLVMValue;

      if (leftExpr.kind === ast.ASTType.PathExpr) {
        const varName = leftExpr.segs[0]!;
        const loaded = this.builder.load(varName);
        currentValue = { register: loaded.register, type: loaded.type, isLValue: false };
      } else if (leftExpr.kind === ast.ASTType.IndexExpr) {
        currentValue = this.handleIndexLoad(leftExpr);
      } else if (leftExpr.kind === ast.ASTType.FieldExpr) {
        currentValue = this.onFieldExpr(leftExpr, this as any);
      } else {
        throw new Error("Invalid assignment target");
      }

      // Apply the operation
      const baseOp = op.substring(0, op.length - 1) as Operator;
      value = {
        register: this.builder.binop(baseOp, currentValue.register, value.register, value.type),
        type: value.type,
        isLValue: false
      };
    }

    // Store the value
    if (leftExpr.kind === ast.ASTType.PathExpr) {
      const varName = leftExpr.segs[0]!;
      this.builder.store(value.register, value.type, varName);
    } else if (leftExpr.kind === ast.ASTType.IndexExpr) {
      this.handleIndexStore(leftExpr, value);
    } else if (leftExpr.kind === ast.ASTType.FieldExpr) {
      this.handleFieldStore(leftExpr, value);
    }

    return value;
  }

  /**
   * Handle loading a value from an array index (for compound assignments).
   */
  private handleIndexLoad(node: ast.IndexExpr): LLVMValue {
    // This is essentially the same as onIndexExpr
    return this.onIndexExpr(node, this as any)!;
  }

  /**
   * Handle storing a value to an array index.
   */
  private handleIndexStore(node: ast.IndexExpr, value: LLVMValue): void {
    // Currently only support variable arrays (PathExpr)
    if (node.arr.kind !== ast.ASTType.PathExpr) {
      throw new Error("Only variable arrays supported in MVP");
    }

    const arrName = (node.arr as ast.PathExpr).segs[0]!;
    const arrType = this.analyzer.getNodeType(node.arr);

    if (!arrType || arrType.kind !== "arrayType") {
      throw new Error("Indexing non-array type");
    }

    const elementType = this.builder.getType(arrType.type);

    // Generate index value
    const idxValue = ast.visit(node.idx, this)!;

    // Get array allocation
    const alloc = this.builder.getAllocation(arrName);
    if (!alloc) {
      throw new Error(`Array ${arrName} not allocated`);
    }

    // GEP to get element pointer
    const idxType = idxValue.type; // Use the actual type of the index (i32 for i32, i64 for usize)
    const gepReg = this.builder.getelementptr(
      alloc.type,
      alloc.allocaRegister,
      [
        { value: "0", type: "i32" },
        { value: idxValue.register, type: idxType }
      ]
    );

    // Store value
    this.builder.emitInstruction(`store ${elementType} ${value.register}, ptr ${gepReg}`);
  }

  /**
   * Handle storing a value to a struct field.
   */
  private handleFieldStore(node: ast.FieldExpr, value: LLVMValue): void {
    const objectType = this.analyzer.getNodeType(node.object);
    if (!objectType || objectType.kind !== "structType") {
      throw new Error("Field access requires struct type");
    }

    // Find the field index
    const fieldNames = Array.from(objectType.fields.keys());
    const fieldIndex = fieldNames.indexOf(node.field);
    if (fieldIndex === -1) {
      throw new Error(`Field ${node.field} not found in struct`);
    }

    // Get the field type
    const fieldType = objectType.fields.get(node.field);
    if (!fieldType) {
      throw new Error(`Field ${node.field} has no type`);
    }
    const fieldLlvmType = this.builder.getType(fieldType);

    // Get the object's address (not value!)
    let objPtr: string;
    let objLlvmType: string;

    if (node.object.kind === ast.ASTType.PathExpr) {
      // For simple variable access, use the alloca address directly
      const varName = (node.object as ast.PathExpr).segs[0]!;
      const alloc = this.builder.getAllocation(varName);
      if (!alloc) {
        throw new Error(`Variable ${varName} not allocated`);
      }
      objPtr = alloc.allocaRegister;
      objLlvmType = alloc.type;

      // Special case for self parameter: self is a pointer stored in an alloca
      // We need to load the pointer before doing GEP
      if (varName === "self" && alloc.type === "ptr") {
        const loadedPtr = this.builder.freshRegister();
        this.builder.emitInstruction(`${loadedPtr} = load ptr, ptr ${objPtr}`);
        objPtr = loadedPtr;
        // objLlvmType should be the struct type for GEP
        objLlvmType = this.builder.getType(objectType);
      }
    } else {
      // For complex expressions (e.g., nested field access), use the result
      const object = ast.visit(node.object, this)!;
      objPtr = object.register;
      objLlvmType = object.type;
    }

    // GEP to get field address
    const gepReg = this.builder.getelementptr(
      objLlvmType,
      objPtr,
      [
        { value: "0", type: "i32" },
        { value: fieldIndex.toString(), type: "i32" }
      ]
    );

    // Store field value
    this.builder.emitInstruction(`store ${fieldLlvmType} ${value.register}, ptr ${gepReg}`);
  }

  /**
   * Visit a unary expression.
   */
  onUnaryExpr(node: ast.UnaryExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    const operand = ast.visit(node.operand, this)!;

    // Handle dereference (*) specially - need to get the pointed-to type
    if (node.operator === "*") {
      // Get the type of the operand
      let operandType = this.analyzer.getNodeType(node.operand);

      // Fallback 1: try to get type from symbol table for parameters
      if (!operandType && node.operand.kind === ast.ASTType.PathExpr) {
        const varName = (node.operand as ast.PathExpr).segs[0]!;
        const varSymbol = this.symbolTable.lookupVariable(varName);
        if (varSymbol) {
          operandType = varSymbol.type;
        }
      }

      // Fallback 2: try to get type from current function's parameters
      if (!operandType && node.operand.kind === ast.ASTType.PathExpr && this.currentFunction) {
        const varName = (node.operand as ast.PathExpr).segs[0]!;
        const funcSym = this.symbolTable.lookupFunction(this.currentFunction.name);
        if (funcSym) {
          // Check if it's the self parameter (for impl methods)
          if (varName === "self" && funcSym.self) {
            // Self parameter: construct reference type to struct
            // For now, just skip - will be handled by other fallbacks or error
          } else {
            // Check regular parameters
            for (let i = 0; i < this.currentFunction.params.length; i++) {
              const param = this.currentFunction.params[i];
              if (param && param.pattern.kind === ast.ASTType.IdentifierPattern) {
                const paramName = (param.pattern as ast.IdentifierPattern).name;
                if (paramName === varName) {
                  // Get the parameter type from funcSym.params
                  // Note: funcSym.params doesn't include self, so index is i
                  if (i < funcSym.params.length) {
                    operandType = funcSym.params[i];
                  }
                  break;
                }
              }
            }
          }
        }
      }

      if (!operandType) {
        // Debug: print what we're looking for
        console.error(`DEBUG: Type not found for dereference operand`);
        console.error(`  node.operand.kind: ${ast.ASTType[node.operand.kind]}`);
        if (node.operand.kind === ast.ASTType.PathExpr) {
          const varName = (node.operand as ast.PathExpr).segs[0]!;
          console.error(`  varName: ${varName}`);
          console.error(`  currentFunction: ${this.currentFunction?.name}`);
        }
        throw new Error("Type not found for dereference operand");
      }

      // For reference types, get the underlying type
      let loadedType: string;
      if (operandType.kind === "refType") {
        loadedType = this.builder.getType(operandType.under);
      } else if (operandType.kind === "primitiveType" && operandType.name === "usize") {
        // Raw pointer (usize) - assume i32 for now
        loadedType = "i32";
      } else {
        throw new Error(`Cannot dereference non-reference type: ${operandType.kind}`);
      }

      const resultReg = this.builder.freshRegister();
      this.builder.emitInstruction(`${resultReg} = load ${loadedType}, ptr ${operand.register}`);
      return { register: resultReg, type: loadedType, isLValue: false };
    }

    const resultReg = this.builder.unaryOp(node.operator, operand.register, operand.type);
    return { register: resultReg, type: operand.type, isLValue: false };
  }

  /**
   * Visit a path expression (variable reference).
   */
  onPathExpr(node: ast.PathExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    if (node.segs.length !== 1) {
      throw new Error("Complex paths not supported in MVP");
    }

    const varName = node.segs[0]!;

    // Get type from semantic analysis
    let varType = this.analyzer.getNodeType(node);
    let llvmType: string | undefined;

    // Fallback: look up in symbol table (for function parameters)
    if (!varType) {
      const varSymbol = this.symbolTable.lookupVariable(varName);
      if (varSymbol) {
        varType = varSymbol.type;
      }
    }

    // Another fallback: check allocation to get type (for function parameters)
    if (!varType) {
      const alloc = this.builder.getAllocation(varName);
      if (alloc) {
        // The allocation has the type in the form "ptr" or "i32" etc.
        // We need to infer the semantic type from the LLVM type
        llvmType = alloc.type;
      }
    }

    if (!varType && !llvmType) {
      throw new Error(`Type not found for variable: ${varName}`);
    }

    if (!llvmType) {
      llvmType = this.builder.getType(varType!);
    }

    // Load from stack allocation
    const loaded = this.builder.load(varName);
    return { register: loaded.register, type: llvmType, isLValue: false };
  }

  /**
   * Visit an index expression (array indexing).
   */
  onIndexExpr(node: ast.IndexExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    // Currently only support variable arrays (PathExpr)
    if (node.arr.kind !== ast.ASTType.PathExpr) {
      throw new Error("Only variable arrays supported in MVP");
    }

    const arrName = (node.arr as ast.PathExpr).segs[0]!;
    const arrType = this.analyzer.getNodeType(node.arr);

    if (!arrType || arrType.kind !== "arrayType") {
      throw new Error("Indexing non-array type");
    }

    const elementType = this.builder.getType(arrType.type);

    // Generate index value
    const idxValue = ast.visit(node.idx, this)!;

    // Get array allocation
    const alloc = this.builder.getAllocation(arrName);
    if (!alloc) {
      throw new Error(`Array ${arrName} not allocated`);
    }

    // GEP: get pointer to element
    // For array[index], we need: ptr, i32 0, <index-type> index
    const idxType = idxValue.type; // Use the actual type of the index (i32 for i32, i64 for usize)
    const gepReg = this.builder.getelementptr(
      alloc.type,
      alloc.allocaRegister,
      [
        { value: "0", type: "i32" },  // First index (array itself)
        { value: idxValue.register, type: idxType }  // Element index with correct type
      ]
    );

    // Load the element value
    const loadedReg = this.builder.freshRegister();
    this.builder.emitInstruction(`${loadedReg} = load ${elementType}, ptr ${gepReg}`);

    return { register: loadedReg, type: elementType, isLValue: false };
  }

  /**
   * Visit a function call.
   */
  onCallExpr(node: ast.CallExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get function name
    let funcName: string;
    let argValues = node.param.map((arg) => ast.visit(arg, this)!);

    let funcSym: FunctionSymbol | undefined
    // Check for method call or associated function syntax (Type::method or object.method)
    if (node.value.kind === ast.ASTType.PathExpr) {
      const pathExpr = node.value as ast.PathExpr;
      const segs = pathExpr.segs;

      if (segs.length === 2) {
        // This could be:
        // 1. Associated function: Type::method(args)
        // 2. Method call on variable: obj.method(args)

        const firstSeg = segs[0]!;
        const secondSeg = segs[1]!;

        // First, try to look up as a variable (for method calls)
        const objSymbol = this.symbolTable.lookupVariable(firstSeg);

        if (objSymbol) {
          // Method call on object (e.g., stack.push())
          const methodName = secondSeg;
          const objVarName = firstSeg;

          const objType = objSymbol.type;
          if (objType.kind !== "structType") {
            throw new Error(`Method call requires struct type, got ${objType.kind}`);
          }

          // Find the method in the struct
          if (!objType.methods || !objType.methods.has(methodName)) {
            throw new Error(`Method ${methodName} not found in struct ${objType.name}`);
          }

          funcSym = objType.methods.get(methodName)!;
          funcName = `${objType.name}_${methodName}`;

          // Prepend the object as the first argument (self)
          const firstParam = funcSym.params[0];
          if (!firstParam) {
            throw new Error(`Method ${methodName} has no parameters`);
          }

          const objValue: LLVMValue = {
            register: `%${objVarName}`,
            type: this.builder.getType(firstParam),
            isLValue: false
          };

          argValues = [objValue, ...argValues];
        } else {
          // Associated function call (e.g., Counter::new())
          // Look up the type
          const structType = this.symbolTable.lookupType(firstSeg);
          if (!structType || structType.kind !== "structType") {
            throw new Error(`Type ${firstSeg} not found or is not a struct`);
          }

          const methodName = secondSeg;

          // Find the method in the struct
          if (!structType.methods || !structType.methods.has(methodName)) {
            throw new Error(`Method ${methodName} not found in struct ${structType.name}`);
          }

          funcSym = structType.methods.get(methodName)!;
          funcName = `${structType.name}_${methodName}`;
        }
      } else if (segs.length === 1) {
        // Regular function call
        funcName = segs[0]!;
        funcSym = this.symbolTable.lookupFunction(funcName);
        if (!funcSym) {
          throw new Error(`Undefined function: ${funcName}`);
        }
      } else {
        throw new Error("Complex function calls not supported in MVP");
      }
    } else if (node.value.kind === ast.ASTType.FieldExpr) {
      // Method call using field access syntax (e.g., c.increment())
      const fieldExpr = node.value as ast.FieldExpr;
      const methodName = fieldExpr.field;

      // Get the object type
      const objectType = this.analyzer.getNodeType(fieldExpr.object);
      if (!objectType || objectType.kind !== "structType") {
        throw new Error("Method call requires struct type");
      }

      // Find the method in the struct
      if (!objectType.methods || !objectType.methods.has(methodName)) {
        throw new Error(`Method ${methodName} not found in struct ${objectType.name}`);
      }

      funcSym = objectType.methods.get(methodName)!;
      funcName = `${objectType.name}_${methodName}`;

      // Get the object's address (not value!)
      let objPtr: string;
      let objLlvmType: string;

      if (fieldExpr.object.kind === ast.ASTType.PathExpr) {
        // For simple variable access, use the alloca address directly
        const varName = (fieldExpr.object as ast.PathExpr).segs[0]!;
        const alloc = this.builder.getAllocation(varName);
        if (!alloc) {
          throw new Error(`Variable ${varName} not allocated`);
        }
        objPtr = alloc.allocaRegister;
        objLlvmType = alloc.type;
      } else {
        // For complex expressions (e.g., nested field access), use the result
        const object = ast.visit(fieldExpr.object, this)!;
        objPtr = object.register;
        objLlvmType = object.type;
      }

      // Construct the self parameter type
      // Methods with self have the self parameter info in funcSym.self
      let selfType: Type;
      if (funcSym.self) {
        // Self parameter: construct reference type based on mutability
        selfType = {
          kind: "refType",
          mutable: funcSym.self.mutable,
          under: objectType
        };
      } else {
        // No self parameter (shouldn't happen for methods called via field access)
        throw new Error(`Method ${methodName} has no self parameter`);
      }

      const objValue: LLVMValue = {
        register: objPtr,
        type: this.builder.getType(selfType),
        isLValue: false
      };

      argValues = [objValue, ...argValues];
    } else {
      throw new Error(`Complex function calls not supported in MVP: node.value.kind = ${ast.ASTType[node.value.kind]}`);
    }

    if (!funcSym) {
      throw new Error(`Undefined function: ${funcName}`);
    }

    // Build arguments list
    const args = argValues.map((v) => ({ value: v.register, type: v.type }));

    // Get return type
    const retType = this.builder.getType(funcSym.returnType);

    // Emit call
    const resultReg = this.builder.call(retType, funcName, args);

    if (resultReg) {
      return { register: resultReg, type: retType, isLValue: false };
    } else {
      return null;
    }
  }

  /**
   * Visit a let statement (variable declaration).
   */
  onLet(node: ast.LetStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    let varName: string;
    if (node.pattern.kind === ast.ASTType.IdentifierPattern) {
      varName = (node.pattern as ast.IdentifierPattern).name;
    } else {
      throw new Error("Only identifier patterns supported in MVP");
    }

    // Get variable type from semantic analysis
    const patternType = this.analyzer.getNodeType(node.pattern);
    if (!patternType) {
      throw new Error(`Type not found for variable ${varName}`);
    }

    const varType = this.builder.getType(patternType);

    // Allocate stack space
    this.builder.alloca(varName, varType);

    // Store initial value if provided
    if (node.expr) {
      const initType = this.analyzer.getNodeType(node.expr);

      // Check if this is an array initialization
      if (node.expr.kind === ast.ASTType.ArrayExpr) {
        this.initializeArray(varName, node.expr as ast.ArrayExpr, patternType);
      } else if (node.expr.kind === ast.ASTType.RepeatArrayExpr) {
        this.initializeRepeatArray(varName, node.expr as ast.RepeatArrayExpr, patternType);
      } else if (node.expr.kind === ast.ASTType.StructExpr) {
        // For struct initialization, initialize directly to variable's allocation
        this.initializeStruct(varName, node.expr as ast.StructExpr, patternType);
      } else {
        // Regular variable initialization
        const initValue = ast.visit(node.expr, this)!;
        this.builder.store(initValue.register, varType, varName);
      }
    }

    return null;
  }

  /**
   * Initialize an array from an ArrayExpr.
   */
  private initializeArray(varName: string, node: ast.ArrayExpr, arrayType: Type): void {
    if (arrayType.kind !== "arrayType") {
      throw new Error("ArrayExpr for non-array type");
    }

    const elementType = this.builder.getType(arrayType.type);
    const alloc = this.builder.getAllocation(varName);

    if (!alloc) {
      throw new Error(`Array ${varName} not allocated`);
    }

    // Store each element
    for (let i = 0; i < node.val.length; i++) {
      const elemExpr = node.val[i]!;
      const elemValue = ast.visit(elemExpr, this)!;

      // GEP to get element pointer
      const gepReg = this.builder.getelementptr(
        alloc.type,
        alloc.allocaRegister,
        [
          { value: "0", type: "i32" },
          { value: i.toString(), type: "i32" }
        ]
      );

      // Store element
      this.builder.emitInstruction(`store ${elementType} ${elemValue.register}, ptr ${gepReg}`);
    }
  }

  /**
   * Initialize an array from a RepeatArrayExpr.
   */
  private initializeRepeatArray(varName: string, node: ast.RepeatArrayExpr, arrayType: Type): void {
    if (arrayType.kind !== "arrayType") {
      throw new Error("RepeatArrayExpr for non-array type");
    }

    const elementType = this.builder.getType(arrayType.type);
    const alloc = this.builder.getAllocation(varName);

    if (!alloc) {
      throw new Error(`Array ${varName} not allocated`);
    }

    // Generate the value to repeat
    const value = ast.visit(node.val, this)!;

    // Get repeat count (semantic analyzer should have evaluated this to a constant)
    const repeatCount = arrayType.size;

    // Store the value in each element
    for (let i = 0; i < repeatCount; i++) {
      const gepReg = this.builder.getelementptr(
        alloc.type,
        alloc.allocaRegister,
        [
          { value: "0", type: "i32" },
          { value: i.toString(), type: "i32" }
        ]
      );

      this.builder.emitInstruction(`store ${elementType} ${value.register}, ptr ${gepReg}`);
    }
  }

  /**
   * Initialize a struct from a StructExpr.
   */
  private initializeStruct(varName: string, node: ast.StructExpr, structType: Type): void {
    if (structType.kind !== "structType") {
      throw new Error("StructExpr for non-struct type");
    }

    const alloc = this.builder.getAllocation(varName);
    if (!alloc) {
      throw new Error(`Struct ${varName} not allocated`);
    }

    const llvmType = alloc.type;

    // Initialize each field
    for (const field of node.fields) {
      const fieldType = structType.fields.get(field.name);
      if (!fieldType) {
        throw new Error(`Field ${field.name} not found in struct`);
      }

      // Generate the field value
      const value = ast.visit(field.value, this)!;
      const fieldLlvmType = this.builder.getType(fieldType);

      // Get field index (GEP needs sequential indices starting from 0)
      const fieldNames = Array.from(structType.fields.keys());
      const fieldIndex = fieldNames.indexOf(field.name);
      if (fieldIndex === -1) {
        throw new Error(`Field ${field.name} not found`);
      }

      // GEP to get field address
      const gepReg = this.builder.getelementptr(
        llvmType,
        alloc.allocaRegister,
        [
          { value: "0", type: "i32" },
          { value: fieldIndex.toString(), type: "i32" }
        ]
      );

      // Store field value
      this.builder.emitInstruction(`store ${fieldLlvmType} ${value.register}, ptr ${gepReg}`);
    }
  }

  /**
   * Visit a return expression.
   */
  onReturnExpr(node: ast.ReturnExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (node.expr) {
      const value = ast.visit(node.expr, this)!;
      if (this.currentReturnType !== "void") {
        this.builder.ret(value.register);
      } else {
        throw new Error("Cannot return value from void function");
      }
    } else {
      if (this.currentReturnType === "void") {
        this.builder.ret();
      } else {
        throw new Error("Must return value from non-void function");
      }
    }
    return null;
  }

  /**
   * Visit an if expression.
   */
  onIf(node: ast.IfExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Generate condition
    const cond = ast.visit(node.cond, this)!;

    // Create labels
    const thenLabel = this.builder.freshLabel("if.then");
    const elseLabel = this.builder.freshLabel("if.else");
    const endLabel = this.builder.freshLabel("if.end");

    // Conditional branch
    this.builder.condBr(cond.register, thenLabel, elseLabel);

    // Then block
    this.builder.label(thenLabel);
    const thenValue = ast.visit(node.then, this);
    // Only branch to end if the then block doesn't already terminate
    if (!this.exprTerminates(node.then)) {
      this.builder.br(endLabel);
    }

    // Else block (if present)
    let elseValue: LLVMValue | null = null;
    if (node.else) {
      this.builder.label(elseLabel);
      const visitedElse = ast.visit(node.else, this);
      elseValue = visitedElse ?? null;
      // Only branch to end if the else block doesn't already terminate
      if (!this.exprTerminates(node.else)) {
        this.builder.br(endLabel);
      }
    } else {
      this.builder.label(elseLabel);
      this.builder.br(endLabel);
    }

    // Merge block (only if we haven't terminated)
    const thenTerminates = this.exprTerminates(node.then);
    const elseTerminates = node.else ? this.exprTerminates(node.else) : false;
    if (!thenTerminates || !elseTerminates) {
      this.builder.label(endLabel);
    }

    // Handle if-value (if both branches produce values)
    if (thenValue && elseValue && thenValue.type === elseValue.type) {
      const phiReg = this.builder.phi(thenValue.type, [
        { value: thenValue.register, label: thenLabel },
        { value: elseValue.register, label: elseLabel },
      ]);
      return { register: phiReg, type: thenValue.type, isLValue: false };
    }

    return null;
  }

  /**
   * Visit a while expression.
   */
  onWhile(node: ast.WhileExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Create labels
    const condLabel = this.builder.freshLabel("while.cond");
    const bodyLabel = this.builder.freshLabel("while.body");
    const endLabel = this.builder.freshLabel("while.end");

    // Push loop context onto stack
    this.loopStack.push({
      breakLabel: endLabel,
      continueLabel: condLabel
    });

    // Entry: branch to condition
    this.builder.br(condLabel);

    // Condition block
    this.builder.label(condLabel);
    const cond = ast.visit(node.cond, this)!;
    this.builder.condBr(cond.register, bodyLabel, endLabel);

    // Body block
    this.builder.label(bodyLabel);
    ast.visit(node.body, this);
    this.builder.br(condLabel);

    // End block
    this.builder.label(endLabel);

    // Pop loop context
    this.loopStack.pop();

    return null;
  }

  /**
   * Visit a break expression.
   */
  onBreakExpr(node: ast.BreakExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (this.loopStack.length === 0) {
      throw new Error("break statement outside of loop");
    }

    const breakLabel = this.loopStack[this.loopStack.length - 1]!.breakLabel;

    // Note: while loops ignore break values (unlike loop expressions)
    if (node.expr) {
      ast.visit(node.expr, this);
    }

    this.builder.br(breakLabel);
    return null;
  }

  /**
   * Visit a continue expression.
   */
  onContinueExpr(_node: ast.ContinueExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    if (this.loopStack.length === 0) {
      throw new Error("continue statement outside of loop");
    }

    const continueLabel = this.loopStack[this.loopStack.length - 1]!.continueLabel;
    this.builder.br(continueLabel);
    return null;
  }

  /**
   * Visit an expression statement.
   */
  onExprStatement(node: ast.ExprStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    ast.visit(node.expr, this);
    return null;
  }

  /**
   * Visit an empty statement.
   */
  onEmptyStatement(_node: ast.EmptyStatement, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    return null;
  }

  /**
   * Visit a struct declaration.
   */
  onStruct(node: ast.StructItem, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get the struct type from semantic analysis
    const structType = this.analyzer.getNodeType(node);
    if (!structType || structType.kind !== "structType") {
      throw new Error(`Struct type not found for ${node.name}`);
    }

    // Build field list for LLVM struct definition from the struct type
    const fields = node.fields.map(field => {
      const fieldType = structType.fields.get(field.name);
      if (!fieldType) {
        throw new Error(`Type not found for field ${field.name}`);
      }
      const llvmType = this.builder.getType(fieldType);
      return { name: field.name, type: llvmType };
    });

    // Define the struct type in LLVM IR
    this.builder.defineStruct(structType.UUID, node.name, fields);

    return null;
  }

  /**
   * Visit a struct expression (struct literal initialization).
   */
  onStructExpr(node: ast.StructExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get the struct type
    const structType = this.analyzer.getNodeType(node);
    if (!structType || structType.kind !== "structType") {
      throw new Error("Struct expression must have struct type");
    }

    // Allocate stack space for the struct
    const llvmType = this.builder.getType(structType);
    const tempName = `struct.${this.builder.freshRegister()}`;
    const allocaReg = this.builder.freshRegister();
    this.builder.emitInstruction(`${allocaReg} = alloca ${llvmType}`);

    // Initialize each field
    for (const field of node.fields) {
      const fieldType = structType.fields.get(field.name);
      if (!fieldType) {
        throw new Error(`Field ${field.name} not found in struct`);
      }

      // Generate the field value
      const value = ast.visit(field.value, this)!;
      const fieldLlvmType = this.builder.getType(fieldType);

      // Get field index (GEP needs sequential indices starting from 0)
      const fieldNames = Array.from(structType.fields.keys());
      const fieldIndex = fieldNames.indexOf(field.name);
      if (fieldIndex === -1) {
        throw new Error(`Field ${field.name} not found`);
      }

      // GEP to get field address
      const gepReg = this.builder.getelementptr(
        llvmType,
        allocaReg,
        [
          { value: "0", type: "i32" },
          { value: fieldIndex.toString(), type: "i32" }
        ]
      );

      // Store field value
      this.builder.emitInstruction(`store ${fieldLlvmType} ${value.register}, ptr ${gepReg}`);
    }

    // Return the struct value (as a pointer to the allocated memory)
    return { register: allocaReg, type: llvmType, isLValue: true };
  }

  /**
   * Visit a field access expression (object.field).
   */
  onFieldExpr(node: ast.FieldExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue {
    // Get the object type
    const objectType = this.analyzer.getNodeType(node.object);
    if (!objectType || objectType.kind !== "structType") {
      throw new Error("Field access requires struct type");
    }

    // Find the field index
    const fieldNames = Array.from(objectType.fields.keys());
    const fieldIndex = fieldNames.indexOf(node.field);
    if (fieldIndex === -1) {
      throw new Error(`Field ${node.field} not found in struct`);
    }

    // Get the field type
    const fieldType = objectType.fields.get(node.field);
    if (!fieldType) {
      throw new Error(`Field ${node.field} has no type`);
    }
    const fieldLlvmType = this.builder.getType(fieldType);

    // Get the object's address (not value!)
    let objPtr: string;
    let objLlvmType: string;

    if (node.object.kind === ast.ASTType.PathExpr) {
      // For simple variable access, use the alloca address directly
      const varName = (node.object as ast.PathExpr).segs[0]!;
      const alloc = this.builder.getAllocation(varName);
      if (!alloc) {
        throw new Error(`Variable ${varName} not allocated`);
      }
      objPtr = alloc.allocaRegister;
      objLlvmType = alloc.type;

      // Special case for self parameter: self is a pointer stored in an alloca
      // We need to load the pointer before doing GEP
      if (varName === "self" && alloc.type === "ptr") {
        const loadedPtr = this.builder.freshRegister();
        this.builder.emitInstruction(`${loadedPtr} = load ptr, ptr ${objPtr}`);
        objPtr = loadedPtr;
        // objLlvmType should be the struct type for GEP
        objLlvmType = this.builder.getType(objectType);
      }
    } else {
      // For complex expressions (e.g., nested field access), use the result
      const object = ast.visit(node.object, this)!;
      objPtr = object.register;
      objLlvmType = object.type;
    }

    // GEP to get field address
    const gepReg = this.builder.getelementptr(
      objLlvmType,
      objPtr,
      [
        { value: "0", type: "i32" },
        { value: fieldIndex.toString(), type: "i32" }
      ]
    );

    // Load the field value
    const loadedReg = this.builder.freshRegister();
    this.builder.emitInstruction(`${loadedReg} = load ${fieldLlvmType}, ptr ${gepReg}`);

    return { register: loadedReg, type: fieldLlvmType, isLValue: false };
  }

  /**
   * Visit const item (global constant).
   */
  onConst(node: ast.ConstItem, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // For now, treat const as a global variable
    const sym = this.symbolTable.lookupVariable(node.name);
    if (!sym) {
      throw new Error(`Const ${node.name} not found in symbol table`);
    }

    const varType = this.builder.getType(sym.type);

    // Evaluate constant value
    if (node.val && node.val.kind === ast.ASTType.LiteralExpr) {
      const lit = node.val as ast.LiteralExpr;
      let value: string;
      if (lit.type === "integer") {
        value = this.builder.literalI32(parseInt(lit.value, 10));
      } else if (lit.type === "bool") {
        value = this.builder.literalBool(lit.value === "true");
      } else {
        throw new Error(`Unsupported const literal type: ${lit.type}`);
      }
      this.builder.emitInstruction(`@${node.name} = global ${varType} ${value}`);
    } else {
      throw new Error("Only literal constants supported in MVP");
    }
    return null;
  }

  /**
   * Visit an impl block.
   */
  onImpl(node: ast.InherentImpl, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get the struct name
    const structName = node.type.value;

    // Look up the struct type
    const structType = this.symbolTable.lookupType(structName);
    if (!structType || structType.kind !== "structType") {
      throw new Error(`Impl block for non-struct type: ${structName}`);
    }

    // Visit each function in the impl block
    // We need to rename them to StructName_method_name
    for (const func of node.fn) {
      const originalName = func.name;
      const mangledName = `${structName}_${originalName}`;

      // Get the method symbol from the struct's methods map
      const methodSym = structType.methods?.get(originalName);
      if (!methodSym) {
        throw new Error(`Method ${originalName} not found in struct ${structName}`);
      }

      // Temporarily insert the mangled function into the global symbol table
      // so that onFn can find it
      const tempFuncSym: FunctionSymbol = {
        ...methodSym,
        name: mangledName
      };
      this.symbolTable.insertFunction(mangledName, tempFuncSym);

      // Temporarily change the function name for code generation
      func.name = mangledName;
      ast.visit(func, this);
      func.name = originalName;  // Restore original name

      // Note: We don't remove the mangled function from the symbol table
      // because it might be referenced later in the code
    }

    return null;
  }

  /**
   * Visit a cast expression (expr as Type).
   */
  onCastExpr(node: ast.CastExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // Get the source expression value
    const srcValue = ast.visit(node.expr, this)!;

    // Get the source and target types
    // For cast expressions, the type of the expression is the target type
    const srcType = this.analyzer.getNodeType(node.expr);
    const targetType = this.analyzer.getNodeType(node);

    if (!srcType) {
      throw new Error("Type not found for cast expression source");
    }
    if (!targetType) {
      throw new Error("Type not found for cast expression target");
    }

    const srcLlvmType = this.builder.getType(srcType);
    const targetLlvmType = this.builder.getType(targetType);

    // Generate appropriate cast instruction based on type sizes
    let resultReg: string;

    // Determine size comparison for integer casts
    const getSize = (llvmType: string): number => {
      if (llvmType === "i1") return 1;
      if (llvmType === "i8") return 8;
      if (llvmType === "i16") return 16;
      if (llvmType === "i32") return 32;
      if (llvmType === "i64") return 64;
      return 32; // default
    };

    const srcSize = getSize(srcLlvmType);
    const targetSize = getSize(targetLlvmType);

    if (srcSize < targetSize) {
      // Zero-extend to larger type
      resultReg = this.builder.zext(srcValue.register, srcLlvmType, targetLlvmType);
    } else if (srcSize > targetSize) {
      // Truncate to smaller type
      resultReg = this.builder.trunc(srcValue.register, srcLlvmType, targetLlvmType);
    } else {
      // Same size, use bitcast or just pass through
      resultReg = srcValue.register;
    }

    return { register: resultReg, type: targetLlvmType, isLValue: false };
  }

  /**
   * Visit a borrow expression (&expr or &mut expr).
   */
  onBorrowExpr(node: ast.BorrowExpr, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    // For simple variable references (PathExpr), get the alloca address directly
    if (node.expr.kind === ast.ASTType.PathExpr) {
      const varName = (node.expr as ast.PathExpr).segs[0]!;
      const alloc = this.builder.getAllocation(varName);
      if (alloc) {
        // Return the alloca address as a pointer
        return { register: alloc.allocaRegister, type: "ptr", isLValue: false };
      }
    }

    // For field access (FieldExpr), get the alloca address
    if (node.expr.kind === ast.ASTType.FieldExpr) {
      const fieldExpr = node.expr as ast.FieldExpr;
      const objectType = this.analyzer.getNodeType(fieldExpr.object);
      if (!objectType || objectType.kind !== "structType") {
        throw new Error("Field access requires struct type");
      }

      // Find the field index
      const fieldNames = Array.from(objectType.fields.keys());
      const fieldIndex = fieldNames.indexOf(fieldExpr.field);
      if (fieldIndex === -1) {
        throw new Error(`Field ${fieldExpr.field} not found in struct`);
      }

      // Get the object's address
      let objPtr: string;
      let objLlvmType: string;

      if (fieldExpr.object.kind === ast.ASTType.PathExpr) {
        const varName = (fieldExpr.object as ast.PathExpr).segs[0]!;
        const alloc = this.builder.getAllocation(varName);
        if (!alloc) {
          throw new Error(`Variable ${varName} not allocated`);
        }
        objPtr = alloc.allocaRegister;
        objLlvmType = alloc.type;

        // Special case for self parameter
        if (varName === "self" && alloc.type === "ptr") {
          const loadedPtr = this.builder.freshRegister();
          this.builder.emitInstruction(`${loadedPtr} = load ptr, ptr ${objPtr}`);
          objPtr = loadedPtr;
          objLlvmType = this.builder.getType(objectType);
        }
      } else {
        throw new Error("Complex field access not supported for borrow");
      }

      // GEP to get field address
      const gepReg = this.builder.getelementptr(
        objLlvmType,
        objPtr,
        [
          { value: "0", type: "i32" },
          { value: fieldIndex.toString(), type: "i32" }
        ]
      );

      // Return the field address as a pointer
      return { register: gepReg, type: "ptr", isLValue: false };
    }

    // For other expressions, visit and handle
    const innerValue = ast.visit(node.expr, this)!;

    // For lvalues (struct expressions, etc.), the register is already an address
    if (innerValue.isLValue) {
      // Return the address directly
      return { register: innerValue.register, type: "ptr", isLValue: false };
    } else {
      // For rvalues, we need to allocate temporary storage and store the value
      const tempReg = this.builder.freshRegister();
      this.builder.emitInstruction(`${tempReg} = alloca ${innerValue.type}`);
      this.builder.emitInstruction(`store ${innerValue.type} ${innerValue.register}, ptr ${tempReg}`);

      return { register: tempReg, type: "ptr", isLValue: false };
    }
  }

  /**
   * Default handler for unhandled node types.
   */
  default(node: ast.ASTNode, _self: ast.Visitor<LLVMValue | null>): LLVMValue | null {
    throw new Error(`Unhandled AST node type: ${ast.ASTType[node.kind]}`);
  }
}
